apiVersion: agones.dev/v1
kind: Fleet

metadata:
  name: velocity
  namespace: emortalmc

spec:
  replicas: 1
  scheduling: Packed

  strategy:
    type: Recreate # Don't do Rolling, or we'll have two Proxies running at once (trying to use the same port)

  template:
    spec:
      ports:
        - name: default
          portPolicy: Static
          hostPort: 25565
          containerPort: 25565
          protocol: TCP

      counters:
        players:
          count: 0

      lists:
        players:
          values: [ ]

      health:
        initialDelaySeconds: 10
        periodSeconds: 6
        failureThreshold: 2

      template:
        spec:
          serviceAccountName: default-gameserver
          automountServiceAccountToken: true

          containers:
            - name: velocity
              image: "ghcr.io/emortalmc/velocity-core:{{ .Values.version }}"

              command: [ "java" ]
              args: [ "--enable-preview", "-XX:+UseZGC", "-Xmx3G", "-Xms3G", "-jar", "/app/velocity.jar" ]

              lifecycle:
                postStart:
                  exec:
                    command: [ "/bin/sh", "-c", "echo $VELOCITY_FORWARDING_SECRET > /app/forwarding.secret" ]

              resources:
                requests:
                  memory: "4Gi"
                  cpu: "500m"
                limits:
                  memory: "4Gi"
                  cpu: "6"

              env:
                - name: VELOCITY_FORWARDING_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: velocity-forwarding-token
                      key: forwarding.secret
                      optional: false
                - name: KAFKA_HOST
                  value: default-kafka-bootstrap
                - name: KAFKA_PORT
                  value: "9092"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: FLEET_NAME
                  value: velocity