apiVersion: agones.dev/v1
kind: Fleet

metadata:
  name: velocity
  namespace: emortalmc

spec:
  replicas: 2
  scheduling: Packed

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%

  template:
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 25565
          protocol: TCP

      counters:
        players:
          count: 0

      lists:
        players:
          values: [ ]

      health:
        initialDelaySeconds: 10
        periodSeconds: 6
        failureThreshold: 2

      template:
        spec:
          serviceAccountName: default-gameserver
          automountServiceAccountToken: true

          containers:
            - name: velocity
              image: "ghcr.io/emortalmc/velocity-core:{{ .Values.version }}"

              command: [ "java" ]
              args: [ "--enable-preview", "-XX:+UseZGC", "-Xmx6G", "-Xms5G", "-jar", "/app/velocity.jar" ]

              lifecycle:
                postStart:
                  exec:
                    command: [ "/bin/sh", "-c", "echo $VELOCITY_FORWARDING_SECRET > /app/forwarding.secret" ]

              resources:
                requests:
                  memory: "12Gi"
                  cpu: "500m"
                limits:
                  memory: "12Gi"
                  cpu: "12"

              env:
                - name: VELOCITY_FORWARDING_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: velocity-forwarding-token
                      key: forwarding.secret
                      optional: false
                - name: KAFKA_HOST
                  value: default-kafka-bootstrap
                - name: KAFKA_PORT
                  value: "9092"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: FLEET_NAME
                  value: velocity
                - name: PYROSCOPE_SERVER_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      name: pyroscope
                      key: address
                - name: EDGE_ROUTING_KEY
                  valueFrom:
                    secretKeyRef:
                      name: edge-routing-token
                      key: routing-token
                      optional: false
