apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.name }}
  namespace: emortalmc
  labels:
    app: {{ .Values.name }}

spec:
  replicas: {{ .Values.replicas }}

  # revisionHistoryLimit the amount of old ReplicaSets to retain to allow rollback to previous application versions.
  revisionHistoryLimit: 15

  selector:
    matchLabels:
      app: {{ .Values.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        linkerd.io/inject: enabled

    spec:
      {{ if .Values.enableLiveConfig }}
      serviceAccountName: {{ .Values.name }}
      automountServiceAccountToken: true
      {{ end }}

      {{ if .Values.enableLiveConfig }}
      volumes:
        - name: gamemodes
          configMap:
            name: gamemodes
            optional: false
      {{ end }}

      containers:
        - name: {{ .Values.name }}
          image: "ghcr.io/emortalmc/{{ default (.Values.name) .Values.imageName }}:{{ .Values.version }}"
          {{ include "service.resources" . | nindent 10 }}

          ports:
            - name: grpc
              containerPort: 9010

          {{ if .Values.enableLiveConfig }}
          volumeMounts:
            - name: gamemodes
              mountPath: /app/config/gamemodes
          {{ end }}
          {{ include "service.env" . | nindent 10 }}
