apiVersion: v1
kind: ConfigMap
metadata:
  name: gamemodes
  namespace: emortalmc
  labels:
    helm.sh/chart: "gamemode-config"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range .Values.gamemodes }}
  {{- $keyName := printf "%s.json" .id }}
  {{- if .priority }}
  {{- $keyName = printf "%d-%s.json" (int .priority) .id }}
  {{- end }}
  {{ $keyName }}: |-
  {{ . | toPrettyJson | nindent 4 }}
  {{- end }}
