apiVersion: v1
kind: ConfigMap
metadata:
  name: gamemodes
  namespace: emortalmc
  labels:
    helm.sh/chart: "gamemode-config"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range .Values.gamemodes }}
  {{ .id }}.json: |-
    {{- . | toJson | nindent 4 }}
  {{- end }}